Glyph rendering some more
planteater/hello-ny pull request #44
Opened 2021-04-21 16:22 UTC by codestreamtest

Glyphs should render with colored icons in the gutter based on state.

2021-04-21 19:52 UTC, planteater commented on api/sessionEvents.ts
> +// upadating some codz
Single from CM

2021-04-21 20:56 UTC, planteater commented
delete me!

2021-04-21 20:57 UTC, planteater commented on agent/agentConnection.ts
> +			return this._connection.sendRequest(FetchPostRepliesRequestType, {
patch this! single

2021-04-21 20:57 UTC, planteater commented on agent/agentConnection.ts
> +			return this._connection.sendRequest(FetchPostRepliesRequestType, {
rep pathc sing

2021-04-21 20:59 UTC, planteater approved these changes
gitterdone 3

2021-04-21 20:59 UTC, planteater commented on agent/agentConnection.ts
> +				postId: parentPostId
now rev 3

2021-04-21 21:00 UTC, planteater reviewed
gitter 4

2021-04-21 21:01 UTC, planteater reviewed
sub 4

2021-04-21 21:01 UTC, planteater commented on agent/agentConnection.ts
> +		}
add 4

2021-04-21 21:02 UTC, planteater commented
dun!

2021-04-21 21:22 UTC, planteater commented
Closing time, again.

2021-04-26 20:58 UTC, planteater commented on configuration.ts
> +}
check it

2021-04-27 13:29 UTC, planteater requested changes
nonono

2021-04-27 13:30 UTC, planteater reviewed
blah bleh

2021-04-27 13:31 UTC, planteater approved these changes
ok lgtm

2021-04-27 13:48 UTC, bcanzanella reviewed
aaa

2021-04-27 13:51 UTC, bcanzanella reviewed
aa

2021-04-27 14:10 UTC, bcanzanella reviewed
lgtm

2021-04-27 14:24 UTC, bcanzanella approved these changes
lgtm

2021-04-27 14:32 UTC, planteater reviewed
go away now?

2021-04-28 14:03 UTC, planteater commented on configuration.ts
> +const emptyBeers: any = new Proxy<any>({} as Config, {
Single before review

2021-04-28 14:03 UTC, planteater commented on configuration.ts
> +const emptyBeers: any = new Proxy<any>({} as Config, {
rep before

2021-04-28 14:04 UTC, planteater reviewed
And now submit da review

2021-04-28 14:04 UTC, planteater commented on configuration.ts
> +		return emptyConfig;
And now starting da review

2021-04-28 14:04 UTC, planteater commented on configuration.ts
> +const emptyBeers: any = new Proxy<any>({} as Config, {
rep after

2021-04-29 13:52 UTC, planteater commented on configuration.ts
> +export interFoo ConfigurationWillChangeEvent {
singlllllle

2021-04-30 13:08 UTC, planteater commented
Comment with a pic!

![WIP MR](https://user-images.githubusercontent.com/3442587/116699499-a3e65500-a993-11eb-8367-af20147a0055.png)

2021-05-12 16:46 UTC, planteater commented
commount

```
			Container.session.onDidChangeSessionStatus(this.onSessionStatusChanged, this)

```
								
[providers/codeActionProvider.ts](https://github.com/planteater/hello-ny/blob/a5eb6a2ca5b27999009f3a30ef63aa705bf63d90/providers/codeActionProvider.ts#L45) (Line 45)

2021-05-14 10:44 UTC, planteater commented
gi

2021-05-19 14:35 UTC, planteater commented on agent/agentConnection.ts
> +			return this._connection.sendRequest(FetchPostRepliesRequestType, {
Comment on 446-447 in diff

2021-05-19 14:41 UTC, planteater commented on agent/agentConnection.ts
> +		fetchMyBeer(streamId: string, parentPostId: string) {
Comment on line 446

2021-05-24 15:20 UTC, closed without merging